### ISSUE TITLE
Datablock Storage - deprecate Firebase (tracking issue)

### ISSUE THREAD

**Issue by snickell** [code-dot-org/code-dot-org#55084]
We're looking to move away from Firebase due to high costs, a security model we never locked down fully, and increased local-dev infrastructure complexity.

Eventually this description will be updated to include more detail, but for now, this is a continuation of an investigation documented in [#54643](https://github.com/code-dot-org/code-dot-org/pull/56279) .

### Data Model
See https://github.com/code-dot-org/code-dot-org/issues/55344 for details on the data model and https://github.com/code-dot-org/code-dot-org/issues/55481 for details on rate limiting and defining performant queries.

### Direct Query via JS to Firebase -> Rails Controller
https://github.com/code-dot-org/code-dot-org/issues/55554 describes some of the investigations we've done while trying to describe the backend storage implementation and https://github.com/code-dot-org/code-dot-org/issues/55853 has the breakdown of essentially the current Firebase interface that's being used today so that we can override it in a systematic way.

The plan is, given a rails controller to interact with the new DB, override FirebaseStorage so we can swap out the storage layer with our new DatablockStorage implementation conditionally.

### Shared Tables and Current Tables
There are a subset of special tables which come from the Data Library. Current Tables (like 'Spotify Top 50') are kept up to date and student projects reference a shared version of that table. Shared tables are copied into the student's project, creating a lot of duplication.

Our design for these is to treat both Shared and Current tables as Shared tables, and add some deduplication logic that essentially treats Shared tables the same as Current tables until the first write on the table. In other words, when a user adds a table from the Data Library to their project, that table will reference a common table and therefore be kept up to date with any changes to that table. On first write, a copy of the table will be made alongside the other tables in the given project, and it will not longer be kept up to date with the main table.

## Technical Decisions & Reasoning
**Which DB engine?** We went with MySql InnoDB for simplicity and consistency with what the project already uses for backend storage.

**Rollout, incremental vs. all-at-once migration** Incremental rollout based on project configuration. This makes it easier to test individual projects in production earlier without turning on the feature, as well as avoid downtime while the db migration happens.

Decisions and reasoning are documented throughout the related issues in this project, but this is a place to summarize those decisions for the future.

## Rollout Plan

Incremental rollout on a project-by-project basis via a column in the projects DB. Decisions on details of rollout (batched or rolling based on project access? Symmetric writes and checking, or no?) TBD.

### Phase 1: design and investigation
- [x] Select architecture to replace Firebase.
    - [x] Evaluate suitability of the simplest architectures first: "just mysql" vs more complex architectures
        - See: https://github.com/code-dot-org/code-dot-org/pull/54643#issuecomment-1789919051
        - [x] Identify Firebase usage in the `apps/` codebase
            - Used by applab for the Data tab / Data Browser UX
                - Probably doesn't need to be realtime
            - Used by applab for the `onRecordEvent` block available to students
            - Referenced by P5lab = "gamelab" in the UX
        - [x] Identify Firebase usage in the `dashboard/` codebase
        - [x] Evaluate usage to determine if we could use a "non realtime" architecture
            - [x] How is P5Lab using it? answer: using `setKeyValue` and `getKeyValue`, not in a way that requires holding a connection
            - [x] Sample student applab Project usage to determine how often the `onRecordEvent` block is used in TOS-valid projects. Results: only 0.02% of projects use it, see: https://github.com/code-dot-org/code-dot-org/pull/54643#issuecomment-1809461422
            - [x] Get approval from Product/Curriculum to drop the `onRecordEvent` block.
- [x] Design a performant schema for Firebase data (~2 billion rows): #55344 see https://github.com/code-dot-org/code-dot-org/issues/55344#issuecomment-1857090632
- [x] Bulk import 1TB of Firebase data
    - [x] Build bulk import tool: see #55189 
    - [x] Evaluate de-duplicating the Firebase data, which has LOTS of stock table datasets, see #55345 

### Phase 2: implement Datablock Storage backend
- [x] Implement skeleton Datablock Storage rails controller backend
  - [x] Support operations in `firebaseStorage.js`
    - [x] TODO: flesh out list of firebaseStorage commands we want to support
  - [ ] Support operations in `firebase_helper.rb`, see full list here: https://github.com/code-dot-org/code-dot-org/issues/55853
    - [ ] table_as_csv()
    - [ ] delete_shared_table()
    - [ ] upload_shared_table()
    - [ ] upload_live_table()
    - [ ] get_shared_table()
    - [ ] get_shared_table_list()
    - [ ] get_library_manifest()
    - [ ] set_library_manifest()

### Phase 3: migrate existing code to Datablock Storage
- [x] Port Data Browser and Data Library React UX to Datablock Storage
  - [x] applab.js: subscribe the redux store to firebase changes
    - [x] applab.js: subscribeToTable() does a firebase .on('child_added') to live refresh table as rows are added
      - [x] UX decision: drop feature and refresh on a page refresh (natural behavior?)
    - [x] applab.js: subscribes to `current_tables` to get a live updating list of tables in the project
      - [x] UX question: when you go to the data tab, is the data auto-refreshed? (is that like a reload?)
      - [x] UX decision: drop keeping the list of tables live refreshed
      - [x] Question: Does this affect blocks too?
  - [x] onDataViewChange(): implements the UX changes for the dataset browser
 - [x] Port applab blocks to Datablock Storage
   - [x] Port `apps/src/storage` (firebaseStorage, firebaseCounters, etc) to use the new architecture
   - [ ] drop onRecordEvent from commands.js, api.js, dropletConfig.js (see drop PR)
   - [x] applab/commands.js: all calls should pass through to firebaseStorage.js, shouldn't need changes (?)
   - [x] applab/api.js: re-exports commands.js, all calls thereby pass through to firebaseStorage, shouldn't need changes
 - [ ] Port gamelab blocks to Datablock Storage
   - [ ] gamelab/commands.js
   - [ ] Confirm: P5Lab is the same thing as gamelab?
- [ ] Port Levelbuilder mode level_data pieces to Datablock Storage
  - [ ] Only need to port all the commands in `firebase_helper.rb`?
  - [ ] `datasets_controller.rb` and `dashboard/app/views/datasets`
    - [ ] Appears to be a CRUD app for managing the stock datasets, probably only in levelbuilder mode, possibly /datasets
    - [ ] Need to migrate this to the Firebase API
    - [ ] @firebase points to `firebase_helper.rb`
  - [ ] `levels_controller.rb`
    - [ ] e.g. /levels/1/edit, lists the `@firebase.get_library_manifest``
- [ ] Port live dataset features to Datablock Storage (see `bin/cron/applab_datasets`)
- [ ] Rate limiting, see https://github.com/code-dot-org/code-dot-org/issues/55481
  - [ ] Design rate limiting
    - [x] what are current rate limits? are they actually enforced?
      - [ ] Current limits are 300 writes per 15s or 600 per 60s. Our insert rate is 6 per s. This is lower than firebase's current limits.
        - [ ] Will this be an issue for microbit projects?
    - [ ] Determine if session-based limiting (per user) works or if we need firebase "global to channel" style limiting
  - [ ] Implement rate limiting
- [ ] Support exported projects, see https://github.com/code-dot-org/code-dot-org/pull/22522

### Phase 4: rollout and migration
- [x] Decide on details of rollout (batched or rolling based on project access? Symmetric writes and checking, or no?)
- [ ] Finish migration Tool
  - [ ] Before migrating, load standard shared tables from `/v3/channels/shared/counters/tables`
    - [ ] see firebase_helper.rb get_shared_table_list()
    - [ ] Inspect firebase key `/v3/channels/shared`
  - [ ] Add a projects flag to indicate backing store
  - [ ] Build project-by-project migration tool to block writes, migrate storage, and flip backing store bit.
  - [ ] Update code that refreshes current tables (those which are stored here: https://console.firebase.google.com/project/cdo-v3-prod/database/cdo-v3-prod/data/~2Fv3~2Fchannels~2Fshared (see comments in PR)

**Comment by snickell** [comment]
After playing with the production DB, I'm a little sobered by its performance characteristics. If we get approval for dropping the `onRecordEvent` block, we're free to depend on the "limited" capabilities of a SQL DB, but we also need to demonstrate there's a straightforward table structure that can handle our load.

- I'm not seeing the detail of analytics we'd need on the firebase side of things, it more has aggregate MB/s in and out rather than a lot of detail on individual IOps. I might have missed something here?
- I'm wondering if our best approach is to instrument the data "blocks" in applab.
- As far as I can tell, these blocks call direct to firebase and currently do not pass through our servers. I'd rather not mess with this for now, because it'll make for a scarier PR to merge just to get some usage data. My thinking is.... what if we log usage data to firebase, which we already know can sustain the desired load?
- My thinking is to maintain this structure (straight to firebase), to lower an risk of production impact, but to randomly select say 1 out of each 1000 of these calls do an extra step and log to Firebase (i.e. 0.1% of data block calls will actually do two firebase calls, the second is to a log structure we define in firebase):
    - log the data block name
    - log the project ID
    - log the user id
- Then we sample for a day or a week or whatever, and this'll give us an idea of how many calls per second of each block type we'll need to handle.
- Finally we can build a synthetic benchmark to replicate this load, and try different mysql data structures.

**Comment by snickell** [comment]
Data block names would be one of: setKeyValue, getKeyValue, createRecord, updateRecord, deleteRecord, readRecords, readRecordsSync, onRecordEvent

While we're at it, would probably be worth also instrumenting gamelab's setKeyValue and getKeyValue.

**Comment by cnbrenci** [comment]
Summary of what we did yesterday: 

We took a look at some of the analytics in firebase and looked at some of the data storage for projects to understand how the data is shaped. We learned:

1. Current data size is ~1TB. Compressed backups are 100GB.
2. Data is stored per project or "channel", separated by tables where each row has an id and a string value containing a JSON object for the row. 

To prototype the new architecture, our plan is to set up an adhoc and slurp a backup of firebase data in to RDS, gather some info about what volume of different operations are happening against firebase and benchmark the RDS instance with the same data. 

So far, we've done:
1. Set up adhoc adhoc-unfirebase
2. Installed google cloud CLI from https://cloud.google.com/sdk/docs/downloads-interactive
3. Used gsutil from gcloud cli to copy backup from google cloud 
    > `gsutil copy gs://cdo-v3-prod-backups/2023-11-21T11:36:23Z_cdo-v3-prod_data.json.gz .`
4. Used https://github.com/uhop/stream-json to create a chunk of prod data to test with. (a single channel)

Next:
Use the sample of json backup from firebase to write something that slurps that data into RDS

**Comment by snickell** [comment]
Opened #55189 to track work toward bulk importing our terabyte of firebase

**Comment by snickell** [comment]
Summary of work on our Firebase import tool (#55189):
- We've done a 100% streaming import to MySQL of a terabyte Firebase JSON dump.
- Streaming necessary because we can't fit the 1TB file in RAM.
- After some perf testing in Ruby/JS, we've written the import tool in C++ to get a less than 48-hr import.
- A small irregularity was found in the Firebase JSON dump: invalid unicode escape sequences.
- We're currently seeing about 150MB/s doing a streaming parse of the JSON and importing the result into a prod-like RDS instance

Next Steps:
1. Test imported data to determine the most performant schema: #55344 
2. Consider deduping Firebase data to remove "stock" tables: #55345

**Comment by cnbrenci** [comment]
Some notes on changes we'll need to make in the codebase to support the new store

1. Data View UX
  - applab.js: subscribe the redux store to firebase changes
    - applab.js: subscribeToTable() does a firebase .on('child_added') to live refresh table as rows are added
      - UX decision: drop feature and refresh on a page refresh (natural behavior?)
    - applab.js: subscribes to `current_tables` to get a live updating list of tables in the project
      - UX question: when you go to the data tab, is the data auto-refreshed? (is that like a reload?)
      - UX decision: drop keeping the list of tables live refreshed
      - Question: Does this affect blocks too?
  - onDataViewChange(): implements the UX changes for the dataset browser
 2. Data Access for Blocks
   - drop onRecordEvent from commands.js, api.js, dropletConfig.js (see drop PR)
   - applab/commands.js, gamelab/commands.js: all calls should pass through to firebaseStorage.js, shouldn't need changes (?)
   - applab/api.js: re-exports commands.js, all calls thereby pass through to firebaseStorage, shouldn't need changes
   - Confirm: P5Lab is the same thing as gamelab?
3. Levelbuilder
  - Only need to port all the commands in `firebase_helper.rb`?
    - table_as_csv()
    - delete_shared_table()
    - upload_shared_table()
    - upload_live_table()
    - get_shared_table()
    - get_shared_table_list()
    - get_library_manifest()
    - set_library_manifest()
  - `datasets_controller.rb` and `dashboard/app/views/datasets`
    - Appears to be a CRUD app for managing the stock datasets, probably only in levelbuilder mode, possibly /datasets
    - Need to migrate this to the Firebase API
    - @firebase points to `firebase_helper.rb`
  - `levels_controller.rb`
    - e.g. /levels/1/edit, lists the `@firebase.get_library_manifest``
4. Rate limiting
  - how in rails?
  - what are current rate limits? are they actually enforced?
5. Security
  - Can read/write from any channelID you know
  - BUT, channelIDs are like uuids "unguessable", so you need the channelID shared with you to read/write it
  - Unlike Firebse, cannot read/write whole DB with a well-known API
6. Schema
  - Row Per Record
  - What about column definitions?
  - What about de-dupe "pointers"?
  - What about key/value store?
7. Migration Tool
  - Load standard shared tables from `/v3/channels/shared/counters/tables`
    - see firebase_helper.rb get_shared_table_list()
    - Inspect firebase key `/v3/channels/shared`
  - Migrate key/value store
  - Before migrating, load shared tables first
8. other notes
  - applab.storage (in applab.js) == firebase storage
  - LIVE_DATASETS? in datasets_controller.rb
  - Might need firebase to work with exported projects (!!!)
    - See: https://github.com/code-dot-org/code-dot-org/pull/22522

**Comment by snickell** [comment]
We hashed out a schema that covers everything except rate limiting here: https://github.com/code-dot-org/code-dot-org/issues/55344#issuecomment-1857090632
